import RoomsPage from '@/components/main/Rooms/Rooms'
import React from 'react'
const rooms = [
  {
    id: "1",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "2",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "3",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "4",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "5",
    name: "Luxury 2BHK",
    category: "Apartment",
    price: 8200,
    rating: 4.8,
    reviews: 42,
    location: "Bangalore, India",
    image: "/rooms.jpg",
  },
  {
    id: "6",
    name: "Luxury 2BHK",
    category: "Apartment",
    price: 8200,
    rating: 4.8,
    reviews: 42,
    location: "Bangalore, India",
    image: "/rooms.jpg",
  },
  {
    id: "7",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "8",
    name: "Cozy Studio Apartment",
    category: "Studio",
    price: 5000,
    rating: 4.5,
    reviews: 35,
    location: "Mumbai, India",
    image: "/rooms.jpg",
  },
  {
    id: "9",
    name: "Luxury 2BHK",
    category: "Apartment",
    price: 8200,
    rating: 4.8,
    reviews: 42,
    location: "Bangalore, India",
    image: "/rooms.jpg",
  },
  {
    id: "10",
    name: "Luxury 2BHK",
    category: "Apartment",
    price: 8200,
    rating: 4.8,
    reviews: 42,
    location: "Bangalore, India",
    image: "/rooms.jpg",
  },
  {
    id: "11",
    name: "Luxury 2BHK",
    category: "Apartment",
    price: 8200,
    rating: 4.8,
    reviews: 42,
    location: "Bangalore, India",
    image: "/rooms.jpg",
  },
  {
    id: "12",
    name: "Shared PG for Girls",
    category: "PG",
    price: 3000,
    rating: 4.3,
    reviews: 28,
    location: "Pune, India",
    image: "/rooms.jpg",
  },
  {
    id: "13",
    name: "Shared PG for Girls",
    category: "PG",
    price: 3000,
    rating: 4.3,
    reviews: 28,
    location: "Pune, India",
    image: "/rooms.jpg",
  },
  {
    id: "14",
    name: "Shared PG for Girls",
    category: "PG",
    price: 3000,
    rating: 4.3,
    reviews: 28,
    location: "Pune, India",
    image: "/rooms.jpg",
  },
  {
    id: "15",
    name: "Shared PG for Girls",
    category: "PG",
    price: 3000,
    rating: 4.3,
    reviews: 28,
    location: "Pune, India",
    image: "/rooms.jpg",
  },
  {
    id: "16",
    name: "Single Room with Balcony",
    category: "Single Room",
    price: 4500,
    rating: 4.6,
    reviews: 21,
    location: "Delhi, India",
    image: "/rooms.jpg",
  },
  {
    id: "17",
    name: "Single Room with Balcony",
    category: "Single Room",
    price: 4500,
    rating: 4.6,
    reviews: 21,
    location: "Delhi, India",
    image: "/rooms.jpg",
  },
  {
    id: "18",
    name: "Single Room with Balcony",
    category: "Single Room",
    price: 4500,
    rating: 4.6,
    reviews: 21,
    location: "Delhi, India",
    image: "/rooms.jpg",
  },
  {
    id: "19",
    name: "Furnished Room in Apartment",
    category: "Apartment",
    price: 6000,
    rating: 4.4,
    reviews: 18,
    location: "Hyderabad, India",
    image: "/rooms.jpg",
  },
  {
    id: "20",
    name: "Budget PG for Boys",
    category: "PG",
    price: 2500,
    rating: 4.1,
    reviews: 16,
    location: "Chennai, India",
    image: "/rooms.jpg",
  },
];

const page = () => {
  return (
    <div className='pt-30 bg-gray-50'>
      <RoomsPage rooms={rooms} />
    </div>
  )
}

export default page
